### ISSUE TITLE
Requirements for 4.0 release 

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#3125]
This is a list of requirements we need to finish in order to get 4.0 out the door. 

Meta:

- [ ] changelog
- [ ] docs (yt-project/yt#3281)

PRs:

- [x] doc: fix missing `sampling_type` keyword in `add_field` examples yt-project/yt#3123
- [x] No ambiguous fields automatic autofixing yt-project/yt#3101
- [x] rewrite load_sample yt-project/yt#3089
- [x] make energy and momentum field names more accurate and add field deprecation mechanism yt-project/yt#3059
- [x] throw an error if field acceses is ambiguous yt-project/yt#2967
- [x] new depth-first octree yt-project/yt#2400
- [x] enabling phaseplots to have log axis ranges by default yt-project/yt#2213
- [x] changes default weight_field in phaseplot to mass yt-project/yt#2211
- [x] per field config yt-project/yt#1931

Issues: 

- [x] documentation for add_field does not discuss sampling_type yt-project/yt#3108
- [x] reactivate and fix randomly failing answer test yt-project/yt#3069
- [x] broken website examples yt-project/yt#2723
- [x] weighted_variance returns weighted standard deviation yt-project/yt#2713
- [x] add narrative documentation about how the demeshening works yt-project/yt#2629
- [x] update docs for deposited particle fields yt-project/yt#2218
- [x] default phaseplot behavior different for particle and grid datasets yt-project/yt#2212
- [x] profileplot fails on particle-based data with no weight_field set yt-project/yt#2210
- [x] cut regions fail for particle-based fields yt-project/yt#1976
- [x] make ambigous fields accesses an error yt-project/yt#1467
- [x] off_axis_projection can't plot fields which need field parameters yt-project/yt#3126
- [x] ProjectionPlot throws a MPL error when attempting to save() yt-project/yt#2890 

Delayed to yt 4.1:

- [ ] units override should replace unit_base for SPH datasets yt-project/yt#2979
- [ ] octree dataset doesn't support generating ghost zones yt-project/yt#1051
- [ ] error with demeshening in yt accessing deposited fields in arbitrary grids yt-project/yt#2003
- [ ] can no longer do CIC deposit of particle fields in 4.0 yt-project/yt#2205
- [ ] projectionplot defaults to projection units in code units for fields specified as string with center yt-project/yt#1904
- [ ] stop preallocating particles yt-project/yt#2416
- [ ] ds bbox selection bug (periodicity) yt-project/yt#2639

**Comment by munkm** [comment]
I checked off 1976 because @jzuhone updated the docs and added an error to make it clear that particles aren't supported for cut regions yet. I left the issue open until we make a decision about that support.

**Comment by chummels** [comment]
Major releases like yt-4 always have some level of hiccups for the end user, because of backwards-incompatible changes.  One thing that I think could help a great deal with minimizing these hiccups would be:

1) A page in the docs with a high-level description of changes between yt3 and yt4.
2) Documentation on how to convert old scripts to work with yt4.
3) Helpful error messages in the code when someone tries to run an old script and it has failures due to new yt4-related changes.

I think at some level, we're already doing these things. The [yt4 differences doc page](https://yt-project.org/docs/dev/yt4differences.html) has a lot of useful information, and it looks like is doing (1) pretty well.  

I think (2) could be placed here in the same document, with a sort of algorithm that a user can follow to convert their old scripts. So something like: "Search your scripts and replace any field name strings as field name tuples" with an example.

As for (3), I think it's something that we've been doing all along as part of the PR process.  But it might be worth re-visiting this in light of the ensemble of changes in yt4.  In particular, it might be worthwhile to sit down with a friend or colleague who is used to working with the stable version of yt, and take them through the process of the upgrade.  Then have them use their scripts, and see what fails.  On the things that fail, were the error messages obvious as to what needed to change and how to change it?  Did we miss it in our description of "what changed" in yt4 and do we need to include something else in our list of items that users need to account for in converting yt3 scripts to yt4?

Anyway, these are all just ideas from someone who remembers how frustrating it can be to upgrade to a new version and have all of your old scripts break.  We cannot make it automated, but we can help a lot in easing this process for the user.

**Comment by jzuhone** [comment]
The changelog should include a "known issues" section for bugs which we are aware of but aren't fixed before the release.

**Comment by matthewturk** [comment]
I moved all the items that got pushed to 4.1.0 to a separate section.

**Comment by neutrinoceros** [comment]
🎉 Great job team 🎉
