### ISSUE TITLE
Update all docs to reflect yt4 changes and fix breakages

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#3281]
### Bug report

**Bug summary**

I think we need to scan through all of the docs to see where things are broken in yt4.  I've noticed a number of areas where embedded code is broken in the dev docs (e.g., the [notebook embedded in the particle filtering docs](https://yt-project.org/docs/dev/analyzing/filtering.html#filtering-particle-fields)). These corrections should be addressed before we release yt4.  This is in addition to the other docs issues that need to be addressed before yt4 release: Issues #3244 , #3231, #3230, #2629, and #2218.

- [x] Check Introduction to yt docs
- [x] Check yt4 differences docs (Issue #3231)
- [x] Check Installation docs (Issue #3244 -> PR #3350)
- [x] Check Quickstart docs (PR #3306)
- [x] Check Loading and Examining docs (PR #3284)
- [x] Check Cookbook docs (PR #3284)
- [x] Check Visualizing docs (PR #3355)
- [x] Check General Data Analysis docs (PR #3355)
- [x] Check Domain-Specific Analysis docs (PR #3355)
- [x] Check Developer Guide docs (PR #3367)
- [x] Check Sharing Data docs (PR #3355)
- [x] Check Reference Materials docs
- [x] Check FAQ docs (PR #3354)
- [x] Check Help docs (PR #3355)
- [x] Check About yt docs (PR #3355)

We can all work together to check these docs over.  If you encounter an issue in one of the docs, either create a PR to address it, or document it in another Issue before checking off that section in the above list.  We're almost there, everyone!

**Comment by neutrinoceros** [comment]
this looks like a nice complement to the Yt-4.0 meta issue, I'll pin it as well

**Comment by neutrinoceros** [comment]
Just a note that if we want to consider #3244 as a part of this blocker, then #3236 should be discussed as well.

**Comment by matthewturk** [comment]
#3354 checks a box

**Comment by matthewturk** [comment]
#3355 includes my re-reading of all the sections marked as related above.  Notably, I did not do the Reference docs or the Developer docs.

**Comment by matthewturk** [comment]
I've checked off the boxes that were targeted in now-closed PRs

**Comment by neutrinoceros** [comment]
I think we should collectively decide wether #3369 should be added to this list. With the current heavy updates in the documentation, the chances to introduce mistakes (broken refs, invalid code...) seems high. I think we need to keep an eye on the logs to avoid introducing new mistakes while we check all the boxes here :)

**Comment by matthewturk** [comment]
@neutrinoceros I think we should probably include it.  It's almost done anyway, thanks to your hard work, right?!

**Comment by neutrinoceros** [comment]
I got halfway there, but the remaining half is full of mysteries to me. Maybe it _could_ be solved easily, just not by me, I think :)

**Comment by neutrinoceros** [comment]
🎉 Great job team 🎉
