### ISSUE TITLE
checking yt command line options for yt-4.0

### ISSUE THREAD

**Issue by jzuhone** [yt-project/yt#3360]
This issue is meant to track which command-line options work and which don't, in an effort to fix anything major before the yt-4.0 release.

Some of these are being fixed in PR #3361.

- [x] help
- [x] bugreport (uses Bitbucket, removed in #3361 )
- [x] hub register (removed in #3363)
- [x] hub start (see error message below, removed in #3363)
- [x] instinfo
- [x] version
- [x] load
- [x] mapserver (loads, but is really easy to trigger `GenerationInProgress` errors if you click on a field that doesn't exist, fixed in #3361)
- [x] pastebin (generally works, but randomly fails with xmlrpc errors)
- [x] pastebin_grab
- [x] upload_notebook
- [x] plot
- [ ] rpdb (keep getting a "Connection refused.  Is the server running?" message)
- [x] notebook
- [x] stats (prints stats, but does not print max and min of field as advertised, fixed in #3361)
- [x] update (I checked with an installation from source, seemed to do the right thing, but not sure if it works with conda/pip, can't test until after release!)
- [x] delete_image 
- [x] upload_image (fixed in PR #3361)
- [x] upload
- [x] config (works, but typo in "--local     Store the configuration in the global configuration file." fixed in #3361)
- [x] search
- [x] download

**Comment by jzuhone** [comment]
yt hub start gives error:
```pycon
/Users/jzuhone/Source/yt/yt/utilities/logger.py:4: VisibleDeprecationWarning: The configuration file /Users/jzuhone/.config/yt/ytrc is deprecated in favor of /Users/jzuhone/.config/yt/yt.toml. Currently, both are present. Please manually remove the deprecated one to silence this warning.
Deprecated since v4.0.0. This feature will be removed in v4.1.0
  from yt.config import ytcfg
Traceback (most recent call last):
  File "/Users/jzuhone/miniconda3/envs/py39/bin/yt", line 33, in <module>
    sys.exit(load_entry_point('yt', 'console_scripts', 'yt')())
  File "/Users/jzuhone/Source/yt/yt/utilities/command_line.py", line 1957, in run_main
    args.func(args)
  File "/Users/jzuhone/Source/yt/yt/utilities/command_line.py", line 252, in run
    self(args)
  File "/Users/jzuhone/Source/yt/yt/utilities/command_line.py", line 1186, in __call__
    resp = gc.post(f"/notebook/{_id}")
  File "/Users/jzuhone/miniconda3/envs/py39/lib/python3.9/site-packages/girder_client/__init__.py", line 478, in post
    return self.sendRestRequest('POST', path, parameters, files=files,
  File "/Users/jzuhone/miniconda3/envs/py39/lib/python3.9/site-packages/girder_client/__init__.py", line 463, in sendRestRequest
    raise HttpError(
girder_client.HttpError: HTTP error 400: POST https://girder.hub.yt/api/v1//notebook/579faff47b6f0800011e9f59
Response text: {"message": "No matching route for \"POST 579faff47b6f0800011e9f59\"", "type": "rest"}
```

**Comment by jzuhone** [comment]
Do we want to bother fixing `yt bugreport` or should we just remove it? I don't think it's trivial to fix.

**Comment by neutrinoceros** [comment]
Thank you John for this thorough report, this is extremely valuable !

IMO fixing the ˋbugreport` command isn't worth it if it's not trivial (and you're absolutely right that it likely isn't).

**Comment by neutrinoceros** [comment]
The failures seem to indicate that firefly-api was suddenly removed from PyPI ? I'll investigate this, it seems like a important blocker, and definitely not related to your PR.

**Comment by Xarthisius** [comment]
Addressed `yt hub` failure in #3363

**Comment by neutrinoceros** [comment]
I believe this is completely fixed now
