### ISSUE TITLE
MNT: CPython 3.12 compatibility (progress tracker)

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4689]
Opening this to keep track of exactly where we're at and what's left to do:
- #4625
- #4626
- https://github.com/yt-project/yt/pull/4687
- [ ] future: switch tests with full dependencies to 3.12 (and remove the simple job introduced in #4687). This last step should be done when all optional dependencies with significant build time have cp312 wheels on PyPI. In particular, look out for
   - [x] [h5py](https://pypi.org/simple/h5py/)
   - [ ] [cartopy](https://pypi.org/simple/cartopy/)
   - [x] [netCDF4](https://pypi.org/simple/netCDF4/)
   - [x] [aiohttp](https://pypi.org/simple/aiohttp/)

**Comment by neutrinoceros** [comment]
cartopy doesn't ship cp312 wheels yet but the latest version builds fine on Python 3.12 so it's not a hard requirement to close this issue
